### PR TITLE
Fixing issue #161: EventEmitter memory leak when sockets are heavily reused

### PR DESCRIPTION
**Pull request by martonw**
I tested this fix and apparently it works fine where the original version of needle did not. I am adding some more technical description to the ticket #161 on what this fix does and why.

### CODE REVIEW

**Comment by tomas** [comment]
Looks good, thanks. Is there any way we can test that this fixes does fix #162?

**Comment by tomas** [comment]
I mean programmatically.

**Comment by martonw** [comment]
Hi @tomas - thanks for your quick reply. I think it is not easy to test this case because the issue is less deterministic, but I will have a look what needle's current test suit have, maybe I can put together something for it.

**Comment by martonw** [comment]
Hi again, 

I added a new test file (I think it would not fit to any of the existing ones) with one test case that fails in the original branch and is passed after this fix. I created a new branch for the test based on the last commit from you so you can easily verify that the test actually work by switching to the `Issue-161-test` branch. And it has been merged to the master too.

**Comment by tomas** [comment]
Cool. I'll take a look at it in a while and get back to you.

**Comment by tomas** [comment]
I'm seeing a lot of errors thrown on other tests. I'll dig deeper to see what's going on.

**Comment by tomas** [comment]
Ok, so there's two things. First, is that your test actually passes if I run it on master, which means it's not recreating the behaviour that's supposed to be fixed with this PR. And secondly, the reason why I'm getting errors in other tests is because you're not binding the on_socket_end function:

```js 
  function on_socket_end() { 
    if (!this.writable && this.destroyed === false) {
      this.destroy();
      had_error(new Error('Remote end closed socket abruptly.'))
    }
  }
```

This means that `this`, in that function, does not correspond to the socket so `.writable` and `.destroyed` will always return undefined. Is there any particular reason you decided not to use `.bind`?

**Comment by martonw** [comment]
Hi @tomas,

On your first point: I sohuld have been adding some more explanation to this. So you can check out the  branch called `Issue-161-test` on my forked repo which is in top of your master and only adds a test case that will fail due to #161. To check this you can:
```bash
git clone git@github.com:martonw/needle.git
git checkout Issue-161-test
mocha test/socket_pool_spec.js
```
My master branch (where the PR comes from) already has the fix in place + the new test which will pass due to the fix. You can check by:
```bash
git checkout master
mocha test/socket_pool_spec.js
```

On your second point: there is no issue with *this* in this case since the handler is registered like this: 
```javascript
  socket.on_socket_end = on_socket_end;
  socket.on('end', socket.on_socket_end);
```
But I have that double checked anyway. However, there was an issue in the test itself which has thrown more than 1 exception per run which is apparently not something that mocha likes when tests run in async mode and it seemed that many exceptions come from other test executions. So I fixed this to make sure the done callback is called exactly once. 

But: while I was checking if *this* works properly in the `on_socket_end` function, I have came into a conclusion that even though the function is called, the socket's state will be always `destroyed = true`, so this function is effectively a noop. The reason that node's internal handler on the socket's end event will be called first, which will call socket.destroy(). Code sample from node's _http_client.js:

```javascript
function socketOnEnd() {
  var socket = this;
  var req = this._httpMessage;
  var parser = this.parser;

  if (!req.res && !req.socket._hadError) {
    // If we don't have a response then we know that the socket
    // ended prematurely and we need to emit an error on the request.
    req.emit('error', createHangUpError());
    req.socket._hadError = true;
  }
  if (parser) {
    parser.finish();
    freeParser(parser, req, socket);
  }
  socket.destroy();
}
```
This is true for node versions 0.12.7, 4.4.0 (LTS) and 5.7.1 (latest stable), I have not checked for older node versions though.

p.s.: I added a new test case that would trigger the `on_socket_end` function anyway.

**Comment by martonw** [comment]
Hi @tomas, that seems very odd - (almost) all tests are being passed on my end, now I tested with 4 different node versions. The only change I had to make is to increase certain timeouts - maybe just due to my net connection or geographical location. To be full transparent the difference compared to the master is copied below.

I am attaching the full test output using different node.js versions:
[report-5.7.1.txt](https://github.com/tomas/needle/files/168896/report-5.7.1.txt)
[report-4.4.0.txt](https://github.com/tomas/needle/files/168897/report-4.4.0.txt)
[report-0.12.7.txt](https://github.com/tomas/needle/files/168895/report-0.12.7.txt)

Can you tell me what OS you are using, what node version and what arch (x64 vs. x86)? Also a full test output from you would be useful. (I am on Debian 8.1, x64, different node versions).

```bash

$ git diff
diff --git a/test/decoder_spec.js b/test/decoder_spec.js
index 4100fba..8640bc9 100644
--- a/test/decoder_spec.js
+++ b/test/decoder_spec.js
@@ -6,7 +6,7 @@ var should  = require('should'),
 describe('character encoding', function() {
 
   var url;
-  this.timeout(5000);
+  this.timeout(60000);
 
   describe('test A', function() {
 
diff --git a/test/errors_spec.js b/test/errors_spec.js
index 272e666..0c0cd0a 100644
--- a/test/errors_spec.js
+++ b/test/errors_spec.js
@@ -97,7 +97,7 @@ describe('errors', function(){
         setTimeout(function() {
           errorific.code.should.match(/ENOTFOUND|EADDRINFO/)
           done();
-        }, 200)
+        }, 1000)
       })
 
       it('does not emit a readable event', function(done){

```
	   
So the test code you can use:
```javascript
var needle = require('needle');
var http    = require('http');

var httpAgent = new http.Agent({
    keepAlive: true,
    maxSockets: 1
});

var port = 3001;
var server = http.createServer(function(req, res) {
  res.setHeader('Content-Type', 'application/json')
  res.end('{"foo":"bar"}')
}).listen(port);

var testReqCount = 10;
var successCounter = 0;

for (var i = 0; i < testReqCount; i++) {
  needle.get('localhost:' + port, {agent: httpAgent}, function (err, resp) {
    successCounter++;
    if (testReqCount == successCounter) {
      server.close();
      console.log("test finished");
    }
  });
}

```

which is printing someting like:
```
(node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Socket.addListener (events.js:179:15)
    at Socket.Readable.on (_stream_readable.js:671:33)
    at Socket.once (events.js:204:8)
    at ClientRequest.<anonymous> (/home/marci/github/needle-1.0.0-original/node_modules/needle/lib/needle.js:591:12)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:129:20)
    at tickOnSocket (_http_client.js:493:7)
    at _http_client.js:504:7
    at process._tickCallback (node.js:355:11)
test finished
```

**Comment by martonw** [comment]
Hi again,

I did some debugging on this. Long story short: Linux TCP/IP stack differs from Windows and this also means that behavior of node.js network sockets are dependent on the platform. I am using a virtual linux on a win 8.1 host so eventually my network stack was a windows one. This is the reason why the tests were not producing the same results when you ran it against when I did. Now I tested and fixed to code to run on linux stack as well. 

A bit longer version of the story:
In your long_string_spec.js test this is what actually happens on a linux machine (based on a network capture): needle starts sending a long http post request. After a while google server sends a HTTP 413 (Request entity too large) in a duplex way so in parallel needle still sends the post request body, even though google server already sent a FIN ACK meaning it wants to close the socket. After some time, google eventually send a TCP RST packet and the connection get closed.
What is happening in node.js at the same time: needle sends the request. It receives the HTTP 413 response and it calls the done() handler and the user's response handler. As part of that, it removes the event listener from the socket object's 'end' event (which did not work before my fix). However, after all the callbacks are called, eventually the socket object's end listeners are called due to the TCP RST. But by this time, neither the needle 'on_socket_end' listener, nor the nodejs 'endSocket' listener is there, while - for some reason which I believe is not OK in node's socket implementation - the destroy function is not called. Eventually an exception is thrown from 'nowhere' - or in fact, from the socket's write function where it still attempts to write to a socket which is not connected anymore in the OS level. 
To make needle's 'on_socket_end' workaround work for this case, I modified the code so this handler will be registered only once per socket and it will *not* be removed even if a response is received.

**Comment by tomas** [comment]
Hey @martonw, I finally had the time to check your PR today and it looks good. I'm gonna fix some of the syntax in your test and have this merged.

**Comment by martonw** [comment]
Many thanks @tomas just let me know if you need anything else.

**Pull request merged**
