### PR TITLE
[feature] retry request on error

### PR DESCRIPTION
**Pull request by lucaswxp**
In one of my projects I needed to crawl a large number of web pages, so "socket hangup" errors were very common.

With this pull request it's possible to retry a given request if a some error happens. The new options added are:

```javascript
var opts = {
  retry_request           : true, // (default: false) if should retry request if some ECONNRESET error happens
  retry_request_max   : 5, // max attempts to be made
  retry_request_wait  : 3000, // how much to wait in ms to retry the request
  retry_request_on_error_code : ['ECONNRESET'] // the errors that should trigger a retry, ECONNRESET only by default
}
needle.get('http://google.com', opts);
```

### CODE REVIEW

**Comment by tomas** [comment]
Hi,

Thanks for the PR. I think the use case is very limited, though, so I'm not entirely convinced to merge this into master (the whole point of needle is to stay nimble).  Plus it looks like you modified the indentation, which makes this commit affect the blame history for a huge number of lines in the repository... :S

**Comment by lucaswxp** [comment]
Yeah, 

I could probably make it lighter, with only one option. I kinda got carried away :P
I only disagree about being a very limited use case, in my experience ECONNRESET's are usually recoverable after some timeout and happens more the more concurrent requests you have.

I think giving the user a chance to reconnect is a good feature to have, a lot o libs have analogous options to make reconnection/retries, for instance socket.io

The indentation I can fix, I didn't even noticed, sorry about that.

**Comment by Krisa** [comment]
might not be the cleanest implementation, but definitely +1 for the idea!

**Comment by Krisa** [comment]
Seeing not much is happening on something definitely needed for me, I have created a small module based on Needle: https://github.com/Krisa/node-retries - without needle (so that you can always use the latest version of Needle). 

All base methods (get, post, put, ...) should work, what is definitely not working are streams and pipes.

**Comment by tomas** [comment]
@Krisa your module looks good, so I'm closing this issue for the time being.

I might implement this in the future by wrapping the needle get/post/put/etc methods inside of a function that retries the request based on an error code, as proposed by your implementation. I think that's a cleaner approach than inserting all of that logic within `send_request`.

**Pull request closed without merging**
