### PR TITLE
don't add a key when stringifying arrays

### LINKED ISSUE #210: stringify(obj, prefix) incorrectly converts arrays in objects to hashes
When passing an object that contains an array, `stringify` will convert the array to hashes:

Expected:
```js
options = {selections: ['one', 'two', 'three']};
return stringify(options); // 'selections[]=one&selections[]=two&selections[]=three'
```

Actual:

```js
options = {selections: ['one', 'two', 'three']};
return stringify(options); // 'selections[0]=one&selections[1]=two&selections[2]=three'
```

### PR DESCRIPTION
**Pull request by davidlumley**
Resolves #210

Not completely familiar with the process described for testing. I've generated the docker file but am unsure of how to actually run `npm test` inside the container. Any advice is appreciated so I can add tests for this functionality too ❤️

### CODE REVIEW

**Comment by tomas** [comment]
Ideally a test would ensure that the receiving party gets the expected result, e.g.:

```
http.createServer(function(req, res) {
  // parse request body and maybe return a JSON representation
  res.end(JSON.stringify(parsed))
})

var test_data = { foo: 'bar', list: [...] };
needle.post(server, test_data, function(err, resp, body) {
  should.not.exist(err);
  body.list.should.be.an.Array;
  body.list.length.should.eql(3);
}
```

**Comment by tomas** [comment]
Oh, and you don't really need docker to run the test suite. Just `npm install` and then `npm test`. You can run a specific one by doing `node_modules/.bin/mocha test/my_test.js`.

**Comment by davidlumley** [comment]
The tests I've added pass (as do the other tests for the `stringify` method) but as I use MacOS as a dev environment, so just wanted to make sure my changes weren't breaking other functionality. Sorry for any confusion!

**Comment by tomas** [comment]
Ok, I'll take a look at this when I have a minute. Thanks

**Comment by davidlumley** [comment]
Hey @tomas, just checking in to see if there's anything I can do to help get this PR merged? I know managing open source projects can be a bit of a chore so if there's anything I can do please let me know 💖

**Comment by tomas** [comment]
Hey @davidlumley, I totally forgot about this, sorry. Will test and merge right away.

**Pull request merged**
