### PR TITLE
Made automagic http prepending reliable

### PR DESCRIPTION
**Pull request by sw0o0sh**
Hello, old method of 'automagic' prepending was a bit unreliable. Example, if domain starts with http, or has a directory in the path containing 'http', your method wouldn't work. This simple regular expression should do the trick.

### CODE REVIEW

**Comment by tomas** [comment]
Hm. Wouldn't then changing it to `uri.indexOf('http://')` fix it?

**Comment by sw0o0sh** [comment]
Well, you'd still have issues of case sensitivity for one. Also, http:// can be located in the path of a uri string. Example, urls found on the wayback archive: web.archive.org/date/http://somesite.com/. Third, https is also taken into consideration with the regular expression.

**Comment by tomas** [comment]
That sounds like a pretty rare case to me. I appreciate the contribution, but I don't think I'm merging it. Sorry. :)

**Comment by misterhat** [comment]
I think it's a useful enough merge and not any longer than the old 'solution'. Why wouldn't you merge something that fixes hard-to-find bugs?

**Comment by sw0o0sh** [comment]
I have been building a crawler that automatically generates scraped lists of seed URLs for your needle module to request. This would fix the issues with your url preprender internally, and I wouldn't have to keep making wrapper scripts. Your method of prepending http is imperfect and hardly a selling point with the code backing it. I did not provide you with a rare case but a quite common case, since MANY sites have the format, /outgoing.php?url=http://somesite.com.

**Comment by tomas** [comment]
I think we're not on the same page here. Needle simply appends 'http://' to requests that don't contain 'http' in them. That certainly doesn't affect URLs that DO contain 'http' somewhere else. Just make sure your URL does contain the http:// prefix when performing requests and there shouldn't be any problems.

**Comment by misterhat** [comment]
But just checking for containing 'http' isn't enough as sw0o0sh has shown with two examples. His code fixes any edge cases by making sure that 'http://' or 'https://' is at the beginning of the URI only.

**Comment by hikilaka** [comment]
tomas, you're an idiot for rejecting this fix. sw0o0sh is clearly fixing a *bug* in your project, yet you are oblivious to it's presence. Saying that the rarity of a bug isn't common then proceeding to reject someone trying to help you is neglectful. I've used this library once or twice in the past, however, you've proven your incompetence to me, thus I will no longer be using it.

**Comment by sw0o0sh** [comment]
```javascript
// Will not prepend, url does not resolve (with current state of needle)
needle.get('google.com/search?q=http+status+codes', function(err, res, body) {
	if ( err ) { console.log(err); }
	else {
		console.log(res.req._headers);
	}
});
```

**Comment by misterhat** [comment]
I'd suggest removing the 'http' check completely if you have to manually prepend it yourself anyway for the expected behaviour. The solution sw0o0sh offers is simple and fixes the issue, but if it's not going to be merged, the buggy code shouldn't stick around and be advertised.

**Comment by tomas** [comment]
I was actually about to change my mind but then you called me an idiot. You cannot really expect me to accept a PR after that.

**Comment by misterhat** [comment]
The author of the PR isn't the one who said that, and it has no bearing on the correctness of the code either way.

**Comment by sw0o0sh** [comment]
I truthfully question a man who would let personal disputes get in the way of releasing bug-free and proper open-source code. I guess Tomas isn't about releasing bug-free code and learning from others. I heard Microsoft needs new employees. :)

**Pull request closed without merging**
