### PR TITLE
Fix generation of header for digest auth

### PR DESCRIPTION
**Pull request by killix**
And including an option for proxy "proxy_after_auth".
This option if it true, enable the proxy only after the challenge auth is done.

### CODE REVIEW

**Comment by tomas** [comment]
Does this solution work? I need some specs before I can merge.

**Comment by killix** [comment]
Yes it's work. Nothing change between the old method and my update for digest. Former test should pass but i do not see where is the spec for Digest for check.

**Comment by tomas** [comment]
There aren't, because the previous implementation didn't work. :)

A good starting point is to use the [basic auth tests](https://github.com/tomas/needle/blob/master/test/basic_auth_spec.js).

**Comment by killix** [comment]
ok, i going to check asap.

**Comment by tomas** [comment]
Ping? :)

**Comment by tomas** [comment]
Digest auth was fixed a few releases ago so I'm closing this one. Thanks anyway mate.

**Pull request closed without merging**
