### PR TITLE
Add support for RFC-2069

### PR DESCRIPTION
**Pull request by mslosarek**
PR to resolve: https://github.com/tomas/needle/issues/304

### CODE REVIEW

**Comment by tomas** [comment]
Would you add a test for this? :)

**Comment by mslosarek** [comment]
I can, it will likely be of the auth class itself, not with a request. Is that ok?

**Comment by tomas** [comment]
Sure, no prob

**Comment by mslosarek** [comment]
@tomas added tests for auth.digest

**Comment by tomas** [comment]
No, looks beautiful! Thanks.

**Pull request merged**
