### PR TITLE
Fixed zlib_options used for zlib.BrotliDecompress

### PR DESCRIPTION
**Pull request by Phygon**

### CODE REVIEW

**Comment by Phygon** [comment]
Suggested fix for #314

**Comment by tomas** [comment]
Thanks!

**Comment by tomas** [comment]
Will take a look at this later today.

**Comment by Phygon** [comment]
Can I **bump** this after 2 months without being obtrusive?

**Comment by tomas** [comment]
Yikes, sorry about that. Give me a few minutes and I'll merge this.

**Comment by tomas** [comment]
Ok just published 2.5.2

**Pull request merged**
