### PR TITLE
Added support for default headers.

### PR DESCRIPTION
**Pull request by dr0r**
The options object passed to the defaults method can contain a headers object, just like the options object passed to the request method.

### CODE REVIEW

**Comment by tomas** [comment]
Bump!

**Comment by tomas** [comment]
I like this idea but I'm closing this issue until we get at least one test. :)

**Comment by Xubor** [comment]
Aww! Support for headers in defaults is (still) missing. It was really tough to find what is the problem.
Reopen please?

**Comment by dr0r** [comment]
I'm back around for this. Lots have changed sort of. Will take some care for shortcuts getting higher priority than custom default headers. I wish there were simply no shortcuts :)

**Pull request closed without merging**
