### PR TITLE
switch from new Buffer() to Buffer.from()

### LINKED ISSUE #256: node 10.9: new Buffer deprecation warning
with node 10.9, needle's use of `new Buffer` results in the following appearing on stderr:

```
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead
```

### PR DESCRIPTION
**Pull request by starpit**
avoids deprecation failures in nodejs 10

Fixes #256

### CODE REVIEW

**Comment by tomas** [comment]
Nice, thanks! I think we'd need to update the package.json definition to declare that from now on, Needle requires at least version 4.4.x (that's when I believe `Buffer.from` was introduced).

**Comment by starpit** [comment]
https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding

from: 5.10.0

is that OK?

**Comment by starpit** [comment]
updated package.json

**Comment by tomas** [comment]
That's weird, according to earlier docs it was added in 3.0.0?

https://nodejs.org/docs/v4.5.0/api/buffer.html#buffer_class_method_buffer_from_array

**Comment by starpit** [comment]
that is Buffer.from(array); we will need Buffer.from(string, encoding?)

**Comment by tomas** [comment]
Sorry, wrong link. I meant https://nodejs.org/docs/v4.5.0/api/buffer.html#buffer_class_method_buffer_from_str_encoding

**Comment by starpit** [comment]
huh, weird! i can update the PR to reflect this. thanks!

**Comment by tomas** [comment]
Next week! :)

**Comment by DaTebe** [comment]
Hi, any chance we get a new release including this merge?
Kind regards

**Comment by tomas** [comment]
Yes! Sorry, I've been a bit super busy with other stuff lately.

**Pull request merged**
